# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
production:
  adapter:    mysql
  encoding:   utf8
  reconnect:  false
  database:   zomg_production
  pool:       5
  username:   root
  socket:     /tmp/mysql.sock
